import React, { useEffect, useState } from "react";
import "./App.css";
import Container from "./components/Container/Container";
import axios from "axios";

const hash = window.location.hash
  .substring(1)
  .split("&")
  .reduce(function (initial, item) {
    if (item) {
      var parts = item.split("=");
      initial[parts[0]] = decodeURIComponent(parts[1]);
    }
    return initial;
  }, {});
window.location.hash = "";

function App() {
  const [data, setState] = useState([]);
  const [userID, setID] = useState("");
  const [userTracks, setTracks] = useState("");
  const [isLoaded, changeIsLoaded] = useState(false);
  const [userToken, setTokenState] = useState("");
  const [playlistURL, setPlaylistURL] = useState("default");

  const setToken = () => {
    let _token = hash.access_token;
    if (_token) {
      getData(_token);
      setTokenState(_token);
    }
  };

  let playlistName = "my best of all time playlist";
  let timeFrame = "long_term";

  const getData = (token) => {
    const userAPI = "https://api.spotify.com/v1/me";
    const songAPI =
      "https://api.spotify.com/v1/me/top/tracks?time_range=" +
      timeFrame +
      "&limit=50";

    const getUser = axios.get(userAPI, {
      headers: { Authorization: "Bearer " + token },
    });
    const getSongs = axios.get(songAPI, {
      headers: { Authorization: "Bearer " + token },
    });

    axios.all([getUser, getSongs]).then(
      axios.spread((...allData) => {
        const userData = allData[0];
        const songData = allData[1].data.items;
        console.log(userData);
        setID(userData.data.id);
        console.log(userID);
        setState(songData);
        setTracks(songData.map((song) => song.uri));

        console.log(songData);
        changeIsLoaded(true);
      })
    );
  };

  const createPlaylist = () => {
    return axios({
      method: "POST",
      url: `https://api.spotify.com/v1/me/playlists`,
      data: {
        name: playlistName,
        description: "Playlist generated by Big Bad Dan Cargill",
        public: true,
      },
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: `Bearer ${userToken}`,
      },
    }).then((res) => {
      console.log(res.data.external_urls.spotify);
      populatePlaylist(
        res.data.id,
        userTracks,
        userToken,
        res.data.external_urls.spotify
      );
    });
  };

  const populatePlaylist = (id, tracks, token, URL) => {
    return axios({
      method: "POST",
      url: `https://api.spotify.com/v1/playlists/${id}/tracks`,
      data: {
        uris: tracks,
      },
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
    }).then(
      // (res) => res.data);
      () => setPlaylistURL(URL)
    );
  };

  useEffect(setToken, []);

  return (
    <Container
      isLoaded={isLoaded}
      data={data}
      userToken={userToken}
      playlistURL={playlistURL}
      createPlaylist={createPlaylist}
    />
  );
}

export default App;
